### ISSUE TITLE
Submit my idea

### ISSUE THREAD

**Issue by fayazkhan121** [mozilla/TBTWBuildChallenge#30] opened 2016-05-13 03:50 UTC
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
- Challenge Contact Person Name: Fayaz Khan 
- Campus Name: Abasyn University Peshawar
### Idea Description

_Please answer all of the questions below._
- Idea name:
  Secure your data
- What is the problem you are solving for:
  secure user data from third parties 
- Who encounters that problem (who is your audience - describe them): 
  Me and my team
- How will your tool solve this problem for these people:  
  my tool is solve this problem for people when we search some thing so it make more secure our data 
- What are you going to create (app, add-on, extension, etc.): 
  extension
- What are the next steps for building this tool: 
  first of all with my team build these type of tool and then think about to make a app to 
- Links to additional information: 

no link yet

**Comment by LucyeoH-zz** [comment] 2016-05-16 16:25
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment] 2016-05-17 14:40
Closing this as a dupe of issue #31

**Closed as completed by mikeconley** 2016-05-17 14:40 UTC
